name: 002 - Multiple jobs v3

on:
  push:
    branches: [ main, gha-devel ]
    paths: [ ".github/workflows/002*v3.yml" ]


jobs:
  # Define job #1
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Sleep for a while
        run: sleep 5

      - name: What time is it?
        run: |
          # Write current time to file "message.txt"

          printf 'Job #1: time is ' > message.txt
          date >> message.txt

      - name: Print message
        run: cat message.txt

      - name: Save message
        # Use an action written by the community
        uses: actions/upload-artifact@v3
        # Specify parameters for the action
        # Documentation: https://github.com/actions/upload-artifact/blob/main/action.yml
        with:
          name:  first-job-message  # Mandatory option
          path: message.txt  # Mandatory option
          if-no-files-found: error
          retention-days: 7

  # Define job #2
  second-job:
    runs-on: ubuntu-latest
    needs:  first-job  # Make second-job run after first-job

    steps:
      - name: Sleep for a while
        run: sleep 5

      - name: What time is it?
        run: |
          printf 'Job #2: time is '
          date

      - name: Download message from Job N°1
        uses:  actions/download-artifact@v3
        with:
          name: first-job-message

      - name: Ensure message.txt exists
        # Useful for debugging
        run: |
          pwd
          ls -lah .
          ls -lah message.txt

      - name: Print message from Job N°1
        run: |
          # Make sure the message came from Job #1
          grep --quiet '^Job #1:' message.txt
          
          # Print message
          cat message.txt
