name: 004 - Different runners

on:
  push:
    branches: [ main, gha-devel ]
    paths: [ ".github/workflows/004*.yml" ]


jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Where am I running?
        run: uname

  macos-job:
    runs-on: macos-latest
    steps:
      - name: Where am I running?
        run: uname

  windows-job:
    runs-on: windows-latest
    steps:
      - name: Where am I running?
        shell: cmd
        # We are being explicit about the shell required by this step
        # as Windows runners default to use powershell (which does not have the ver command)

        run: ver

# Refer to GitHub docs for an up-to-date list of hosted runners:
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
#
# GitHub recently introduced more powerful (paid) runners. See here:
# https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners
#
# The list software installed on each runner can be found here:
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#preinstalled-software
#
# Example: list for the ubuntu-22.04 runner
# https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
