name: 004 - Job matrix v3

on:
  push:
    branches: [ main, gha-devel ]
    paths: [ ".github/workflows/004*v3.yml" ]


jobs:
  job-matrix-example:
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'macos-12', 'windows-latest' ]
        python-version: ['3.9', '3.10']

      fail-fast: false  # Do not cancel jobs as soon as a job fails

    runs-on: ${{ matrix.os }}  # Variable is expanded to one of the OSes from the job matrix

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Python version
        run: |
          echo '${{ matrix.os }}'
          
          which python3
          python3 --version

      # Install Python using the actions/setup-python action
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python version one more time
        run: |
          which python3
          python3 --version

      - name: Echo Python script? (Unix)
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: cat scripts/test_dictionary_union.py

      - name: Where am I running? (Win)
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: type scripts\test_dictionary_union.py

      - name: Run Python script
        run: python3 scripts/test_dictionary_union.py
